// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQJ_5R_DM7ISQeLB95qWU9nNjb4JNAJw',
    appId: '1:477538030299:web:1825a9980f5ac7e9ba32fe',
    messagingSenderId: '477538030299',
    projectId: 'smartwashingapp',
    authDomain: 'smartwashingapp.firebaseapp.com',
    storageBucket: 'smartwashingapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyaU4WLtCNhAtuiw21J37p1uTvSNT0uI8',
    appId: '1:477538030299:android:df050e206f06c1a0ba32fe',
    messagingSenderId: '477538030299',
    projectId: 'smartwashingapp',
    storageBucket: 'smartwashingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCk9OoJRGzZ2cDxohvUJkqpQ6ZgOR320',
    appId: '1:477538030299:ios:eaf1250913e04a7fba32fe',
    messagingSenderId: '477538030299',
    projectId: 'smartwashingapp',
    storageBucket: 'smartwashingapp.firebasestorage.app',
    iosBundleId: 'com.example.smartClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCk9OoJRGzZ2cDxohvUJkqpQ6ZgOR320',
    appId: '1:477538030299:ios:eaf1250913e04a7fba32fe',
    messagingSenderId: '477538030299',
    projectId: 'smartwashingapp',
    storageBucket: 'smartwashingapp.firebasestorage.app',
    iosBundleId: 'com.example.smartClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZQJ_5R_DM7ISQeLB95qWU9nNjb4JNAJw',
    appId: '1:477538030299:web:8df6febbc06d911cba32fe',
    messagingSenderId: '477538030299',
    projectId: 'smartwashingapp',
    authDomain: 'smartwashingapp.firebaseapp.com',
    storageBucket: 'smartwashingapp.firebasestorage.app',
  );
}
