// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPO0jgrMJcLHUhrrR7oCns4ss4sQhLEC8',
    appId: '1:1019462478481:web:b792b06b49f4a71122ad30',
    messagingSenderId: '1019462478481',
    projectId: 'walkingmachine',
    authDomain: 'walkingmachine.firebaseapp.com',
    storageBucket: 'walkingmachine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI4EltmKPE_2_3y2Umk_FQQK7zikjeqIE',
    appId: '1:1019462478481:android:7734265f2435552c22ad30',
    messagingSenderId: '1019462478481',
    projectId: 'walkingmachine',
    storageBucket: 'walkingmachine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82rSxg9191c3F3UgYZNAXcPv8D5mJGKc',
    appId: '1:1019462478481:ios:8059244b9c001e4122ad30',
    messagingSenderId: '1019462478481',
    projectId: 'walkingmachine',
    storageBucket: 'walkingmachine.firebasestorage.app',
    iosBundleId: 'com.example.smartClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC82rSxg9191c3F3UgYZNAXcPv8D5mJGKc',
    appId: '1:1019462478481:ios:8059244b9c001e4122ad30',
    messagingSenderId: '1019462478481',
    projectId: 'walkingmachine',
    storageBucket: 'walkingmachine.firebasestorage.app',
    iosBundleId: 'com.example.smartClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPO0jgrMJcLHUhrrR7oCns4ss4sQhLEC8',
    appId: '1:1019462478481:web:f08a43fccb8aebf122ad30',
    messagingSenderId: '1019462478481',
    projectId: 'walkingmachine',
    authDomain: 'walkingmachine.firebaseapp.com',
    storageBucket: 'walkingmachine.firebasestorage.app',
  );
}
